nome=str(input("Digite seu nome completo:")).strip()
print("Seu nome em letras maiúsculas é {},".format(nome.upper()))
print("Seu nome em letras minúsculas é {}".format(nome.lower()))
print("Ao todo seu nome possuí {} letras.".format(nome.__len__()- nome.count(" ")))
print(nome.title())
print("seu primeiro nome tem {} letras".format(nome.find(" ")))
separa=nome.split()
print(separa[0],len(separa[0]))